-- Las Tapas · Supabase schema
-- Run this file in Supabase Dashboard → SQL Editor.
-- The app can keep using its current in-memory store until the API is migrated.

create extension if not exists pgcrypto;

create table if not exists public.menu_categories (
  id text primary key,
  name text not null unique,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  id text primary key,
  category_id text not null references public.menu_categories(id) on update cascade on delete restrict,
  name text not null,
  description text not null default '',
  price numeric(10, 2) not null check (price >= 0),
  available boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  table_number text not null check (char_length(btrim(table_number)) between 1 and 30),
  status text not null default 'nieuw' check (status in ('nieuw', 'bereiden', 'klaar')),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  menu_item_id text not null,
  name text not null,
  price numeric(10, 2) not null check (price >= 0),
  quantity integer not null check (quantity between 1 and 20),
  created_at timestamptz not null default now()
);

create index if not exists menu_items_category_idx
  on public.menu_items(category_id, sort_order, name);

create index if not exists orders_status_created_idx
  on public.orders(status, created_at desc);

create index if not exists order_items_order_idx
  on public.order_items(order_id);

-- Keep updated_at correct whenever a row changes.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists menu_items_set_updated_at on public.menu_items;
create trigger menu_items_set_updated_at
before update on public.menu_items
for each row execute function public.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

-- Seed the menu. Safe to re-run: existing rows are updated, not duplicated.
insert into public.menu_categories (id, name, sort_order) values
  ('tapas', 'Tapas', 1),
  ('hoofdgerechten', 'Hoofdgerechten', 2),
  ('desserts', 'Desserts', 3),
  ('dranken', 'Dranken', 4)
on conflict (id) do update set
  name = excluded.name,
  sort_order = excluded.sort_order;

insert into public.menu_items (id, category_id, name, description, price, sort_order) values
  ('patatas-bravas', 'tapas', 'Patatas Bravas', 'Krokante aardappelen met pikante tomatensaus en aioli', 6.50, 1),
  ('gambas-al-ajillo', 'tapas', 'Gambas al Ajillo', 'Garnalen in knoflook-olijfolie met chilipeper', 9.00, 2),
  ('croquetas', 'tapas', 'Croquetas de Jamón', 'Huisgemaakte kroketten met serranoham (6 stuks)', 7.50, 3),
  ('tortilla', 'tapas', 'Tortilla Española', 'Traditionele aardappel-oeuf omelet, per punt', 5.00, 4),
  ('paella-mixta', 'hoofdgerechten', 'Paella Mixta', 'Paella met kip, zeevruchten en saffraanrijst', 18.50, 1),
  ('pimientos', 'hoofdgerechten', 'Pimientos de Padrón', 'Gegrilde pepers met grof zeezout', 6.00, 2),
  ('churrasco', 'hoofdgerechten', 'Churrasco de Ternera', 'Gegrilde entrecôte met chimichurri en patatas', 22.00, 3),
  ('crema-catalana', 'desserts', 'Crema Catalana', 'Spaanse crème brûlée met kaneel', 6.50, 1),
  ('churros', 'desserts', 'Churros con Chocolate', 'Verse churros met warme chocoladesaus', 5.50, 2),
  ('sangria', 'dranken', 'Sangria (glas)', 'Huisgemaakte sangria met rode wijn en fruit', 5.00, 1),
  ('cerveza', 'dranken', 'Cerveza (Estrella)', 'Spaans bier op de tap, 33cl', 3.50, 2),
  ('tinto', 'dranken', 'Vino Tinto (glas)', 'Spaanse rode wijn van de tap', 4.50, 3),
  ('agua', 'dranken', 'Agua Mineral', 'Fles mineraalwater, plat of bruisend', 2.50, 4)
on conflict (id) do update set
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  sort_order = excluded.sort_order;

-- RLS is enabled by default for client access. The server-side API should use
-- a rotated Supabase secret/service-role key; those keys bypass RLS.
alter table public.menu_categories enable row level security;
alter table public.menu_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists public_read_categories on public.menu_categories;
create policy public_read_categories
on public.menu_categories for select
to anon, authenticated
using (true);

drop policy if exists public_read_available_menu on public.menu_items;
create policy public_read_available_menu
on public.menu_items for select
to anon, authenticated
using (available = true);

-- No anonymous order writes are exposed here. Use the Next.js API with a
-- server-only secret key so menu prices and order validation stay server-side.

-- Enable Supabase Realtime for the kitchen screen. If this statement is already
-- present in the publication, the DO block leaves it unchanged.
do $$
begin
  begin
    alter publication supabase_realtime add table public.orders;
  exception
    when duplicate_object then null;
  end;
end;
$$;

-- Useful view for the kitchen/API.
create or replace view public.orders_with_items
with (security_invoker = true)
as
select
  o.id,
  o.table_number,
  o.status,
  o.note,
  o.created_at,
  o.updated_at,
  coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', oi.menu_item_id,
        'name', oi.name,
        'price', oi.price,
        'quantity', oi.quantity
      ) order by oi.id
    ) filter (where oi.id is not null),
    '[]'::jsonb
  ) as items
from public.orders o
left join public.order_items oi on oi.order_id = o.id
group by o.id;
